1. Let $\textbf{u} = (1, -2, 4)$ and $\textbf{v} = (3,5,1)$ $\textbf{w} = (2,1,-3)$ find:<br>
Answered Below
<br>
<br>
2. Repeat problem 1 with the following column vectors:
\begin{align}
    \textbf{u} &= \begin{bmatrix}
           1 \\
           3 \\
           -4
         \end{bmatrix}, \textbf{v} = \begin{bmatrix}
           2 \\
           1 \\
           5
         \end{bmatrix}, \textbf{w} = \begin{bmatrix}
           3 \\
           -2 \\
           6
         \end{bmatrix}
  \end{align}
<br>
<br>
<br>
3. Let $\textbf{u} = (2,-5,4,6,-3)$, $\textbf{v} = (5,-2,1,-7,-4)$, and $\textbf{w} = (2,1,-3)$ find:<br>
a. $4\textbf{u}-3\textbf{v}$<br>
b. $5\textbf{u}+2\textbf{v}-2\textbf{w}$<br>
c. $\textbf{u} \cdotp \textbf{v}$,$\textbf{v} \cdotp \textbf{w}$, $\textbf{u} \cdotp \textbf{w}$<br>
d. ||$\textbf{u}$||, ||$\textbf{v}$||, ||$\textbf{w}$||<br>
e. If $\theta$ is the angle between $\textbf{u}$  and   $\textbf{v}$, find $\cos{\theta}$.<br>
f. If $\alpha$ is the angle between $\textbf{v}$  and   $\textbf{w}$, find $\cos{\alpha}$.<br>
g. If $\beta$ is the angle between $\textbf{u}$  and   $\textbf{w}$, find $\cos{\beta}$.<br>
h. Find $d(\textbf{u},\textbf{v})$.<br>
i. Find $d(\textbf{w},\textbf{v})$.<br>
j. Find $d(\textbf{u},\textbf{w})$. <br>
k. Find $proj(\textbf{u},\textbf{v})$.<br>
l. Find $proj(\textbf{w},\textbf{v})$.<br>
m. Find $proj(\textbf{u},\textbf{w})$. <br> 
<br>
<br>
4. Normalize each vector:<br>
a. $\textbf{u}$ = (5,-7).<br>
b. $\textbf{v}$ = (1,2,-2,4).<br>
c. $\textbf{w} = (\frac{1}{2},\frac{-1}{3},\frac{3}{4})$.<br>
<br>
<br>
5. Let $\textbf{u} = (1,2,-2)$,$\textbf{v} = (3,-12,4)$ and a scalar $k = -3$: <br>
Find $||u||, ||v||, ||u+v||, ||ku||$.<br>
<br>
<br>
6. Find k so that $\textbf{u}  \ and \  \textbf{v}$ are orthogonal.
a. $\textbf{u} = (3, k, -2), \textbf{v} = (6, -4, -3)$.<br>
b. $\textbf{u} = (5,k,-4,2), \textbf{v} = (1,-3,2,2k)$.<br>
c. $\textbf{u} = (1,7,k+2,-2), \textbf{v} = (3, k, -3,k)$.<br>

1. Let $\textbf{u} = (1, -2, 4)$ and $\textbf{v} = (3,5,1)$ $\textbf{w} = (2,1,-3)$ find:<br>
a. $3\textbf{u}-2\textbf{v}$<br>

**1.a. Answer**
$$
\begin{align}
    3\textbf{u} - 2\textbf{v} &= (3(1), 3(-2), 3(4)) &- (2(3), 2(5), 2(1)) \\
        &= (3,-6, 12) &- (6, 10, 2) \\
        &&= (-3, -16, 10)
\end{align}
$$


In [39]:
import numpy as np
u = np.array([1,-2,4])
v = np.array([3,5,1])
print("3(1), 3(-2), 3(4)",u*3)
print("2(3), 2(5), 2(1)",v*2)
print("Answer:",u*3 - v*2)

3(1), 3(-2), 3(4) [ 3 -6 12]
2(3), 2(5), 2(1) [ 6 10  2]
Answer: [ -3 -16  10]


1.b. $5\textbf{u}+3\textbf{v}-4\textbf{w}$<br>

Let $\textbf{u} = (1, -2, 4)$ and $\textbf{v} = (3,5,1)$ $\textbf{w} = (2,1,-3)$ find:<br>
$$
\begin{align}
    5\textbf{u} + 3\textbf{v} - 4\textbf{w} &= (5(1), 5(-2), 5(4)) + (3(3), 3(5), 3(1)) - (4(2), 4(1), 4(-3)) \\
        &= (5, -10, 20) + (9, 15, 3) - (8, 4, -12) \\
        &= (6, 1, 35)
\end{align}
$$

In [4]:
import numpy as np
u = np.array([1,-2,4])
v = np.array([3,5,1])
w = np.array([2,1,-3])
print("5(1),5(−2),5(4)", u*5)
print("3(3),3(5),3(1)", v*3)
print("4(2),4(1),4(−3)", w*4)
print("u + v - w")
print("ANSWER:", u*5+v*3-w*4)

5(1),5(−2),5(4) [  5 -10  20]
3(3),3(5),3(1) [ 9 15  3]
4(2),4(1),4(−3) [  8   4 -12]
u + v - w
ANSWER: [ 6  1 35]


1.c. $\textbf{u} \cdotp \textbf{v}$,$\textbf{v} \cdotp \textbf{w}$, $\textbf{u} \cdotp \textbf{w}$<br>
Let $\textbf{u} = (1, -2, 4)$ and $\textbf{v} = (3,5,1)$ $\textbf{w} = (2,1,-3)$ find:<br>
$$
   \begin{align*}
       \mathbf{u} \cdot \mathbf{v} &= (1)(3) + (-2)(5) + (4)(1) \\
       &= 3 - 10 + 4 \\
       &= -3
   \end{align*}
 $$

$$
   \begin{align*}
       \mathbf{v} \cdot \mathbf{w} &= (3)(2) + (5)(1) + (1)(-3) \\
       &= 6 + 5 - 3 \\
       &= 8
   \end{align*}
$$
$$
   \begin{align*}
       \mathbf{u} \cdot \mathbf{w} &= (1)(2) + (-2)(1) + (4)(-3) \\
       &= 2 - 2 - 12 \\
       &= -12
   \end{align*}
$$

In [5]:
import numpy as np
u = np.array([1,-2,4])
v = np.array([3,5,1])
w = np.array([2,1,-3])

uvdot = np.dot(u, v)
vwdot = np.dot(v, w)
uwdot = np.dot(u, w)

print("u dot v =", uvdot)
print("v dot w =", vwdot)
print("u dot w =", uwdot)

u dot v = -3
v dot w = 8
u dot w = -12


d. ||$\textbf{u}||, ||$\textbf{v}||, ||$\textbf{w}$||<br>

$$\begin{align*}
 \|\mathbf{u}\| &= \sqrt{1^2 + (-2)^2 + 4^2} \\
    &= \sqrt{1 + 4 + 16} \\
    &= \sqrt{21}\\
  \|\mathbf{v}\| &= \sqrt{3^2 + 5^2 + 1^2} \\
    &= \sqrt{9 + 25 + 1} \\
    &= \sqrt{35}\\
  \|\mathbf{w}\| &= \sqrt{2^2 + 1^2 + (-3)^2} \\
    &= \sqrt{4 + 1 + 9} \\
    &= \sqrt{14}
    \end{align*}
$$

In [13]:
import numpy as np
u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])
normU = np.linalg.norm(u)
normV = np.linalg.norm(v)
normW = np.linalg.norm(w)
print("||u|| =", normU)
print("||v|| =", normV)
print("||w|| =", normW)

||u|| = 4.58257569495584
||v|| = 5.916079783099616
||w|| = 3.7416573867739413


e. If $\theta$ is the angle between $\textbf{u}$  and   $\textbf{v}$, find $\cos{\theta}$.<br>



**E, the latex had a stroke**



In [14]:
import numpy as np
u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
dotProd = np.dot(u, v)
normU = np.linalg.norm(u)
normV = np.linalg.norm(v)
res = dotProd / (normU * normV)
print(res)

-0.11065666703449763


**f**

If $\alpha$ is the angle between $\textbf{v}$  and   $\textbf{w}$, find $\cos{\alpha}$.<br>

In [16]:
import numpy as np
u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])
dotProd = np.dot(v, w)
normV = np.linalg.norm(v)
normW = np.linalg.norm(w)
res = dotProd/(normV * normW)
print(res)

0.36140316116210053


g. If $\beta$ is the angle between $\textbf{u}$  and   $\textbf{w}$, find $\cos{\beta}$.<br>

In [17]:
import numpy as np
u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])
dotProd = np.dot(u, w)
normU = np.linalg.norm(u)
normW = np.linalg.norm(w)
res = dotProd / (normU * normW)
print(res)

-0.6998542122237653


h. Find $d(\textbf{u},\textbf{v})$.<br>


In [18]:
import numpy as np
u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])
diff=u-v
distance = np.linalg.norm(diff)
print(distance)

7.874007874011811


i. Find $d(\textbf{w},\textbf{v})$.<br>

In [19]:
import numpy as np
u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])
diff=w-v
distance = np.linalg.norm(diff)
print(distance)

5.744562646538029


j. Find $d(\textbf{u},\textbf{w})$. <br>

In [21]:
import numpy as np
u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])
diff=u-w
distance = np.linalg.norm(diff)
print(distance)

7.681145747868608


k. Find $proj(\textbf{u},\textbf{v})$.<br>

In [22]:
import numpy as np
u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])
dotProd = np.dot(u,v)
normSqr=np.linalg.norm(v)**2
proj=(dotProd/normSqr)*v
print(proj)

[-0.25714286 -0.42857143 -0.08571429]


l. Find $proj(\textbf{w},\textbf{v})$.<br>

In [23]:
import numpy as np
u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])
dotProd = np.dot(w,v)
normSqr=np.linalg.norm(v)**2
proj=(dotProd/normSqr)*v
print(proj)

[0.68571429 1.14285714 0.22857143]


m. Find $proj(\textbf{u},\textbf{w})$. <br> 

In [24]:
import numpy as np
u = np.array([1, -2, 4])
v = np.array([3, 5, 1])
w = np.array([2, 1, -3])
dotProd = np.dot(u,w)
normSqr=np.linalg.norm(w)**2
proj=(dotProd/normSqr)*w
print(proj)

[-1.71428571 -0.85714286  2.57142857]


# =================================================

# 2.

a. $3\textbf{u}-2\textbf{v}$<br>

In [25]:
import numpy as np
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])
w = np.array([3,-2,6])
print(3*u-2*v)

[ -1   7 -22]


b. $5\textbf{u}+3\textbf{v}-4\textbf{w}$<br>

In [26]:
import numpy as np
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])
w = np.array([3,-2,6])
print(5*u+3*v-4*w)

[ -1  26 -29]


c. $\textbf{u} \cdotp \textbf{v}$,$\textbf{v} \cdotp \textbf{w}$, $\textbf{u} \cdotp \textbf{w}$<br>

In [27]:
import numpy as np
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])
w = np.array([3,-2,6])
dotProdUV= np.dot(u,v)
dotProdVW= np.dot(v,w)
dotProdUW= np.dot(u,w)
print(dotProdUV)
print(dotProdVW)
print(dotProdUW)

-15
34
-27


d. ||$\textbf{u}||, ||$\textbf{v}||, ||$\textbf{w}$||<br>

In [28]:
import numpy as np
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])
w = np.array([3,-2,6])
normU= np.linalg.norm(u)
normV= np.linalg.norm(v)
normW= np.linalg.norm(w)
print(normU)
print(normV)
print(normW)

5.0990195135927845
5.477225575051661
7.0


e. If $\theta$ is the angle between $\textbf{u}$  and   $\textbf{v}$, find $\cos{\theta}$.<br>

In [30]:
import numpy as np
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])
w = np.array([3,-2,6])
prodUV = np.dot(u,v)
normU= np.linalg.norm(u)
normV= np.linalg.norm(v)
res= prodUV/(normU*normV)
print(res)

-0.5370861555295747


f. If $\alpha$ is the angle between $\textbf{v}$  and   $\textbf{w}$, find $\cos{\alpha}$.<br>

In [32]:
import numpy as np
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])
w = np.array([3,-2,6])
prodVW = np.dot(v,w)
normV= np.linalg.norm(v)
normW= np.linalg.norm(w)
res=prodVW/(normV*normW)
print(res)

0.8867889026274118


g. If $\beta$ is the angle between $\textbf{u}$  and   $\textbf{w}$, find $\cos{\beta}$.<br>

In [33]:
import numpy as np
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])
w = np.array([3,-2,6])
prodUW=np.dot(u,w)
normW= np.linalg.norm(w)
normU= np.linalg.norm(u)
res= prodUW/(normW*normU)
print(res)

-0.7564479498187099


h. Find $d(\textbf{u},\textbf{v})$.<br>

In [35]:
import numpy as np
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])
w = np.array([3,-2,6])
diff=u-v
distance = np.linalg.norm(diff)
print(distance)

9.273618495495704


i. Find $d(\textbf{w},\textbf{v})$.<br>

In [36]:
import numpy as np
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])
w = np.array([3,-2,6])
diff=w-v
distance=np.linalg.norm(diff)
print(distance)

3.3166247903554


j. Find $d(\textbf{u},\textbf{w})$. <br>

In [37]:
import numpy as np
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])
w = np.array([3,-2,6])
diff=u-w
distance=np.linalg.norm(diff)
print(distance)

11.357816691600547


k. Find $proj(\textbf{u},\textbf{v})$.<br>

In [39]:
import numpy as np
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])
w = np.array([3,-2,6])
prodUV=np.dot(u,v)
normSqrd=np.linalg.norm(v)**2
proj=(prodUV/normSqrd)*v
print(proj)

[-1.  -0.5 -2.5]


l. Find $proj(\textbf{w},\textbf{v})$.<br>

In [40]:
import numpy as np
u = np.array([1, 3, -4])
v = np.array([2, 1, 5])
w = np.array([3,-2,6])
prodWV=np.dot(w,v)
normSqrd=np.linalg.norm(v)**2
proj=(prodWV/normSqrd)*v
print(proj)

[2.26666667 1.13333333 5.66666667]
